#!/bin/bash

#
#  File:
#    backup_cron
#
#  Module:
#    Backup module
#
#  Authors:
#    Ladislav Slezak <lslezak@suse.cz>
#
#  Description:
#    Start backup module - use predefined profile
#    This script is called from cron
#
# $Id$
#

PROFILE=$1

# check profile name
if [ "$PROFILE" == "" ]; then
    echo "Missing profile name";
    exit 1;
fi

# start backup - set cron mode, set nice level to not slowdown other processes
# set server component testsuite to parse UI requests 
nice -n 15 /usr/lib/YaST2/bin/y2base backup '("cron")' '("'$PROFILE'")' testsuite > /dev/null

