#!/usr/bin/perl -w

use ycp;
use File::Temp;

while ( <STDIN> ) {
    my ($command, $path, $directory) = ycp::ParseCommand ($_);

    if ($command eq 'Read') {
	if ($path eq '.' && defined $directory) {
	    if (!-e $directory) {
		y2error ('Directory '.$directory.' does not exist');
		ycp::Return -1;
	    }
	    my $command = '/bin/df';
	    if (!-x $command) {
		y2error('Cannot execute '.$command.' command');
	    }

	    # esacping quoting
	    $directory =~ s/\"/\\\"/g;
	    $command = `$command -P "$directory"`;
	    # first line of out is the header
	    my @out = split(/\n/, $command);
	       @out = split(/ +/, $out[1]);
	    
	    if (defined $out[3]) {
		ycp::Return $out[3];
	    } else {
		y2error ('Cannot determine the free space - Unknown error');
		ycp::Return -1;
	    }
	} else {
	    y2error ('Wrong arguments');
	    ycp::Return -1;
	}
    } elsif ($command eq 'result') {
	exit 0;
    } else {
        y2error ('Wrong path or arguments');
        ycp::Return -1;
    }
}
